services:
  bt-meter-collector:
    build:
      context: ./bt-meter-collector
    image: ghcr.io/culaja/bt-meter-collector:latest

  ha-device-registrar:
    build:
      context: ./ha-device-registrar
    image: ghcr.io/culaja/ha-device-registrar:latest

  hitachi-yutaki-2016-mqtt-gateway:
    build:
      context: ./hitachi-yutaki-2016-mqtt-gateway
    image: ghcr.io/culaja/hitachi-yutaki-2016-mqtt-gateway:latest

  mqtt-timescale-consumer:
    build:
      context: ./mqtt-timescale-consumer
    image: ghcr.io/culaja/mqtt-timescale-consumer:latest
